print("\nnomor 3\n")
baris = int(input('masukkan jumlah baris : '))
kolom = int(input('masukkan jumlah kolom : '))
if baris==3 and kolom==3:
    print("Matrik A\n")
    xx = int(input('masukkan nilai [1][1] : '))
    xy = int(input('masukkan nilai [1][2] : '))
    xz = int(input('masukkan nilai [1][3] : '))
    yx = int(input('masukkan nilai [2][1] : '))
    yy = int(input('masukkan nilai [2][2] : '))
    yz = int(input('masukkan nilai [2][3] : '))
    zx = int(input('masukkan nilai [3][1] : '))
    zy = int(input('masukkan nilai [3][2] : '))
    zz = int(input('masukkan nilai [3][3] : '))
    print("Matrik B\n")
    a= int(input('masukkan  [1][1] : '))
    b= int(input('masukkan  [1][2] : '))
    c= int(input('masukkan  [1][3] : '))
    d= int(input('masukkan  [2][1] : '))
    e= int(input('masukkan  [2][2] : '))
    f= int(input('masukkan  [2][3] : '))
    g= int(input('masukkan  [3][1] : '))
    h= int(input('masukkan  [3][2] : '))
    i= int(input('masukkan  [3][3] : '))

    print('matriks hasil inputan =')
    print(xx+a,xy+b,xz+c)
    print(yx+d,yy+e,yz+f)
    print(zx+g,zy+h,zz+i)
